#!/usr/bin/env python3
import argparse, json, sys
from pypdf import PdfReader
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import KeepTogether, Paragraph, SimpleDocTemplate, Spacer
def escape(text): return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
def page_chrome(watermark):
 def draw(canvas, document):
  canvas.saveState()
  if watermark: canvas.setFont("Helvetica-Bold", 42); canvas.setFillColor(colors.HexColor("#E5E7EB")); canvas.translate(A4[0] / 2, A4[1] / 2); canvas.rotate(35); canvas.drawCentredString(0, 0, watermark)
  canvas.restoreState(); canvas.saveState(); canvas.setStrokeColor(colors.HexColor("#D1D5DB")); canvas.line(20 * mm, 16 * mm, A4[0] - 20 * mm, 16 * mm); canvas.setFont("Helvetica", 8); canvas.setFillColor(colors.HexColor("#4B5563")); canvas.drawString(20 * mm, 10 * mm, "Generated by report-to-pdf skill"); canvas.drawRightString(A4[0] - 20 * mm, 10 * mm, f"Page {document.page}"); canvas.restoreState()
 return draw
def render(payload, output):
 styles = getSampleStyleSheet(); title = ParagraphStyle("ReportTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=25, leading=31, textColor=colors.HexColor("#111827"), spaceAfter=5 * mm); subtitle = ParagraphStyle("ReportSubtitle", parent=styles["Normal"], fontName="Helvetica", fontSize=11, leading=16, textColor=colors.HexColor("#4B5563"), spaceAfter=10 * mm); heading = ParagraphStyle("SectionHeading", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=14, leading=19, textColor=colors.HexColor("#1D4ED8"), spaceBefore=5 * mm, spaceAfter=2 * mm); body = ParagraphStyle("SectionBody", parent=styles["BodyText"], fontName="Helvetica", fontSize=10.5, leading=16, textColor=colors.HexColor("#1F2937"), spaceAfter=3 * mm); bullet = ParagraphStyle("SectionBullet", parent=body, leftIndent=5 * mm, firstLineIndent=-3 * mm)
 document = SimpleDocTemplate(output, pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm, topMargin=20 * mm, bottomMargin=24 * mm, title=payload["title"]); story = [Paragraph(escape(payload["title"]), title)]
 if payload.get("subtitle"): story.append(Paragraph(escape(payload["subtitle"]), subtitle))
 for section in payload["sections"]:
  content = [Paragraph(escape(section["heading"]), heading)]; values = section["body"] if isinstance(section["body"], list) else [section["body"]]
  for value in values: content.append(Paragraph(("• " if isinstance(section["body"], list) else "") + escape(value).replace("\n", "<br/>"), bullet if isinstance(section["body"], list) else body))
  story.extend([KeepTogether(content), Spacer(1, 1 * mm)])
 chrome = page_chrome(payload.get("watermark")); document.build(story, onFirstPage=chrome, onLaterPages=chrome); return len(PdfReader(output).pages)
parser = argparse.ArgumentParser(); parser.add_argument("--input", required=True); parser.add_argument("--output", required=True); args = parser.parse_args()
try:
 with open(args.input, "r", encoding="utf-8") as source: payload = json.load(source)
 print(json.dumps({"pages": render(payload, args.output)}))
except Exception as error: print(str(error), file=sys.stderr); sys.exit(1)
